### ISSUE TITLE
图形显示错误

### ISSUE THREAD

**Issue by caserangle** [AsQuantum/destiny2_utils#1]
![image](https://github.com/AsQuantum/destiny2_utils/assets/67765858/d8bf656c-cefb-4ec6-a70a-cc0f884be09b)
第二部交换时候右应该是方块高亮，而不是圆圈高亮。虽然是换那个雕像，没大体影响

**Comment by AsQuantum** [comment]
已修复
![image](https://github.com/AsQuantum/destiny2_utils/assets/100147969/1e7f8171-ff9d-4370-aafc-0b3fb901018e)
